//
// QuestionBankVO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankVO: Codable, JSONEncodable, Hashable {

    public var createTime: Date?
    public var description: String?
    public var id: Int64?
    public var picture: String?
    public var questionPage: PageQuestionVO?
    public var title: String?
    public var updateTime: Date?
    public var user: UserVO?
    public var userId: Int64?

    public init(createTime: Date? = nil, description: String? = nil, id: Int64? = nil, picture: String? = nil, questionPage: PageQuestionVO? = nil, title: String? = nil, updateTime: Date? = nil, user: UserVO? = nil, userId: Int64? = nil) {
        self.createTime = createTime
        self.description = description
        self.id = id
        self.picture = picture
        self.questionPage = questionPage
        self.title = title
        self.updateTime = updateTime
        self.user = user
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createTime
        case description
        case id
        case picture
        case questionPage
        case title
        case updateTime
        case user
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createTime, forKey: .createTime)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(picture, forKey: .picture)
        try container.encodeIfPresent(questionPage, forKey: .questionPage)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(updateTime, forKey: .updateTime)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankVO: Identifiable {}
