//
// PostThumbControllerAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PostThumbControllerAPI {

    /**
     doThumb
     
     - parameter postThumbAddRequest: (body) postThumbAddRequest 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func doThumbUsingPOST(postThumbAddRequest: PostThumbAddRequest, apiResponseQueue: DispatchQueue = LearnForumAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: BaseResponseint?, _ error: Error?) -> Void)) -> RequestTask {
        return doThumbUsingPOSTWithRequestBuilder(postThumbAddRequest: postThumbAddRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     doThumb
     - POST /api/post_thumb/
     - parameter postThumbAddRequest: (body) postThumbAddRequest 
     - returns: RequestBuilder<BaseResponseint?> 
     */
    open class func doThumbUsingPOSTWithRequestBuilder(postThumbAddRequest: PostThumbAddRequest) -> RequestBuilder<BaseResponseint?> {
        let localVariablePath = "/api/post_thumb/"
        let localVariableURLString = LearnForumAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: postThumbAddRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<BaseResponseint?>.Type = LearnForumAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
