//
// BaseResponseQuestionVO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct BaseResponseQuestionVO: Codable, JSONEncodable, Hashable {

    public var code: Int?
    public var data: QuestionVO?
    public var message: String?

    public init(code: Int? = nil, data: QuestionVO? = nil, message: String? = nil) {
        self.code = code
        self.data = data
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case data
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

