//
// OrderItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrderItem: Codable, JSONEncodable, Hashable {

    public var asc: Bool?
    public var column: String?

    public init(asc: Bool? = nil, column: String? = nil) {
        self.asc = asc
        self.column = column
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case asc
        case column
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(asc, forKey: .asc)
        try container.encodeIfPresent(column, forKey: .column)
    }
}

