//
// Post.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Post: Codable, JSONEncodable, Hashable {

    public var content: String?
    public var createTime: Date?
    public var favourNum: Int?
    public var id: Int64?
    public var isDelete: Int?
    public var tags: String?
    public var thumbNum: Int?
    public var title: String?
    public var updateTime: Date?
    public var userId: Int64?

    public init(content: String? = nil, createTime: Date? = nil, favourNum: Int? = nil, id: Int64? = nil, isDelete: Int? = nil, tags: String? = nil, thumbNum: Int? = nil, title: String? = nil, updateTime: Date? = nil, userId: Int64? = nil) {
        self.content = content
        self.createTime = createTime
        self.favourNum = favourNum
        self.id = id
        self.isDelete = isDelete
        self.tags = tags
        self.thumbNum = thumbNum
        self.title = title
        self.updateTime = updateTime
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case createTime
        case favourNum
        case id
        case isDelete
        case tags
        case thumbNum
        case title
        case updateTime
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(createTime, forKey: .createTime)
        try container.encodeIfPresent(favourNum, forKey: .favourNum)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isDelete, forKey: .isDelete)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(thumbNum, forKey: .thumbNum)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(updateTime, forKey: .updateTime)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Post: Identifiable {}
