//
// PostFavourQueryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostFavourQueryRequest: Codable, JSONEncodable, Hashable {

    public var current: Int?
    public var pageSize: Int?
    public var postQueryRequest: PostQueryRequest?
    public var sortField: String?
    public var sortOrder: String?
    public var userId: Int64?

    public init(current: Int? = nil, pageSize: Int? = nil, postQueryRequest: PostQueryRequest? = nil, sortField: String? = nil, sortOrder: String? = nil, userId: Int64? = nil) {
        self.current = current
        self.pageSize = pageSize
        self.postQueryRequest = postQueryRequest
        self.sortField = sortField
        self.sortOrder = sortOrder
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case pageSize
        case postQueryRequest
        case sortField
        case sortOrder
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(postQueryRequest, forKey: .postQueryRequest)
        try container.encodeIfPresent(sortField, forKey: .sortField)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}

