//
// PostFavourAddRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostFavourAddRequest: Codable, JSONEncodable, Hashable {

    public var postId: Int64?

    public init(postId: Int64? = nil) {
        self.postId = postId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case postId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(postId, forKey: .postId)
    }
}

