//
// PostAddRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostAddRequest: Codable, JSONEncodable, Hashable {

    public var content: String?
    public var tags: [String]?
    public var title: String?

    public init(content: String? = nil, tags: [String]? = nil, title: String? = nil) {
        self.content = content
        self.tags = tags
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case content
        case tags
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(content, forKey: .content)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(title, forKey: .title)
    }
}

