//
// QuestionBankQuestionAddRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestionAddRequest: Codable, JSONEncodable, Hashable {

    public var questionBankId: Int64?
    public var questionId: Int64?

    public init(questionBankId: Int64? = nil, questionId: Int64? = nil) {
        self.questionBankId = questionBankId
        self.questionId = questionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case questionBankId
        case questionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
    }
}

