//
// QuestionBatchDeleteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBatchDeleteRequest: Codable, JSONEncodable, Hashable {

    public var questionIdList: [Int64]?

    public init(questionIdList: [Int64]? = nil) {
        self.questionIdList = questionIdList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case questionIdList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(questionIdList, forKey: .questionIdList)
    }
}

