//
// QuestionBankQuestion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestion: Codable, JSONEncodable, Hashable {

    public var createTime: Date?
    public var id: String?
    public var questionBankId: Int64?
    public var questionId: String?
    public var questionOrder: Int?
    public var updateTime: Date?
    public var userId: Int64?

    public init(createTime: Date? = nil, id: String? = nil, questionBankId: Int64? = nil, questionId: String? = nil, questionOrder: Int? = nil, updateTime: Date? = nil, userId: Int64? = nil) {
        self.createTime = createTime
        self.id = id
        self.questionBankId = questionBankId
        self.questionId = questionId
        self.questionOrder = questionOrder
        self.updateTime = updateTime
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createTime
        case id
        case questionBankId
        case questionId
        case questionOrder
        case updateTime
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createTime, forKey: .createTime)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
        try container.encodeIfPresent(questionOrder, forKey: .questionOrder)
        try container.encodeIfPresent(updateTime, forKey: .updateTime)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankQuestion: Identifiable {}
