//
// QuestionBankQueryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQueryRequest: Codable, JSONEncodable, Hashable {

    public var current: String?
    public var description: String?
    public var id: Int64?
    public var needQueryQuestionList: Bool?
    public var notId: Int64?
    public var pageSize: String?
    public var picture: String?
    public var searchText: String?
    public var sortField: String?
    public var sortOrder: String?
    public var title: String?
    public var userId: Int64?

    public init(current: String? = nil, description: String? = nil, id: Int64? = nil, needQueryQuestionList: Bool? = nil, notId: Int64? = nil, pageSize: String? = nil, picture: String? = nil, searchText: String? = nil, sortField: String? = nil, sortOrder: String? = nil, title: String? = nil, userId: Int64? = nil) {
        self.current = current
        self.description = description
        self.id = id
        self.needQueryQuestionList = needQueryQuestionList
        self.notId = notId
        self.pageSize = pageSize
        self.picture = picture
        self.searchText = searchText
        self.sortField = sortField
        self.sortOrder = sortOrder
        self.title = title
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case description
        case id
        case needQueryQuestionList
        case notId
        case pageSize
        case picture
        case searchText
        case sortField
        case sortOrder
        case title
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(needQueryQuestionList, forKey: .needQueryQuestionList)
        try container.encodeIfPresent(notId, forKey: .notId)
        try container.encodeIfPresent(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(picture, forKey: .picture)
        try container.encodeIfPresent(searchText, forKey: .searchText)
        try container.encodeIfPresent(sortField, forKey: .sortField)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankQueryRequest: Identifiable {}
