//
// QuestionBankUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankUpdateRequest: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var id: Int64?
    public var picture: String?
    public var title: String?

    public init(description: String? = nil, id: Int64? = nil, picture: String? = nil, title: String? = nil) {
        self.description = description
        self.id = id
        self.picture = picture
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case id
        case picture
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(picture, forKey: .picture)
        try container.encodeIfPresent(title, forKey: .title)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankUpdateRequest: Identifiable {}
