//
// QuestionBankQuestionQueryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestionQueryRequest: Codable, JSONEncodable, Hashable {

    public var current: Int?
    public var id: Int64?
    public var notId: Int64?
    public var pageSize: Int?
    public var questionBankId: Int64?
    public var questionId: Int64?
    public var sortField: String?
    public var sortOrder: String?
    public var userId: Int64?

    public init(current: Int? = nil, id: Int64? = nil, notId: Int64? = nil, pageSize: Int? = nil, questionBankId: Int64? = nil, questionId: Int64? = nil, sortField: String? = nil, sortOrder: String? = nil, userId: Int64? = nil) {
        self.current = current
        self.id = id
        self.notId = notId
        self.pageSize = pageSize
        self.questionBankId = questionBankId
        self.questionId = questionId
        self.sortField = sortField
        self.sortOrder = sortOrder
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case current
        case id
        case notId
        case pageSize
        case questionBankId
        case questionId
        case sortField
        case sortOrder
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(current, forKey: .current)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(notId, forKey: .notId)
        try container.encodeIfPresent(pageSize, forKey: .pageSize)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
        try container.encodeIfPresent(sortField, forKey: .sortField)
        try container.encodeIfPresent(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankQuestionQueryRequest: Identifiable {}
