//
// QuestionBankQuestionBatchAddRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestionBatchAddRequest: Codable, JSONEncodable, Hashable {

    public var questionBankId: Int64?
    public var questionIdList: [Int64]?

    public init(questionBankId: Int64? = nil, questionIdList: [Int64]? = nil) {
        self.questionBankId = questionBankId
        self.questionIdList = questionIdList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case questionBankId
        case questionIdList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionIdList, forKey: .questionIdList)
    }
}

