//
// QuestionBankQuestionUpdateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestionUpdateRequest: Codable, JSONEncodable, Hashable {

    public var id: Int64?
    public var questionBankId: Int64?
    public var questionId: Int64?

    public init(id: Int64? = nil, questionBankId: Int64? = nil, questionId: Int64? = nil) {
        self.id = id
        self.questionBankId = questionBankId
        self.questionId = questionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case questionBankId
        case questionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankQuestionUpdateRequest: Identifiable {}
