//
// QuestionBankQuestionVO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct QuestionBankQuestionVO: Codable, JSONEncodable, Hashable {

    public var createTime: Date?
    public var id: Int64?
    public var questionBankId: Int64?
    public var questionId: Int64?
    public var tagList: [String]?
    public var updateTime: Date?
    public var user: UserVO?
    public var userId: Int64?

    public init(createTime: Date? = nil, id: Int64? = nil, questionBankId: Int64? = nil, questionId: Int64? = nil, tagList: [String]? = nil, updateTime: Date? = nil, user: UserVO? = nil, userId: Int64? = nil) {
        self.createTime = createTime
        self.id = id
        self.questionBankId = questionBankId
        self.questionId = questionId
        self.tagList = tagList
        self.updateTime = updateTime
        self.user = user
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createTime
        case id
        case questionBankId
        case questionId
        case tagList
        case updateTime
        case user
        case userId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createTime, forKey: .createTime)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(questionBankId, forKey: .questionBankId)
        try container.encodeIfPresent(questionId, forKey: .questionId)
        try container.encodeIfPresent(tagList, forKey: .tagList)
        try container.encodeIfPresent(updateTime, forKey: .updateTime)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(userId, forKey: .userId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension QuestionBankQuestionVO: Identifiable {}
