//
// UserUpdateMyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserUpdateMyRequest: Codable, JSONEncodable, Hashable {

    public var userAvatar: String?
    public var userName: String?
    public var userProfile: String?

    public init(userAvatar: String? = nil, userName: String? = nil, userProfile: String? = nil) {
        self.userAvatar = userAvatar
        self.userName = userName
        self.userProfile = userProfile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userAvatar
        case userName
        case userProfile
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userAvatar, forKey: .userAvatar)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encodeIfPresent(userProfile, forKey: .userProfile)
    }
}

