//
// UserLoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserLoginRequest: Codable, JSONEncodable, Hashable {

    public var userAccount: String?
    public var userPassword: String?

    public init(userAccount: String? = nil, userPassword: String? = nil) {
        self.userAccount = userAccount
        self.userPassword = userPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userAccount
        case userPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(userAccount, forKey: .userAccount)
        try container.encodeIfPresent(userPassword, forKey: .userPassword)
    }
}

