//
// UserVO.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserVO: Codable, JSONEncodable, Hashable {

    public var createTime: Date?
    public var id: Int64?
    public var userAvatar: String?
    public var userName: String?
    public var userProfile: String?
    public var userRole: String?

    public init(createTime: Date? = nil, id: Int64? = nil, userAvatar: String? = nil, userName: String? = nil, userProfile: String? = nil, userRole: String? = nil) {
        self.createTime = createTime
        self.id = id
        self.userAvatar = userAvatar
        self.userName = userName
        self.userProfile = userProfile
        self.userRole = userRole
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createTime
        case id
        case userAvatar
        case userName
        case userProfile
        case userRole
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createTime, forKey: .createTime)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(userAvatar, forKey: .userAvatar)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encodeIfPresent(userProfile, forKey: .userProfile)
        try container.encodeIfPresent(userRole, forKey: .userRole)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UserVO: Identifiable {}
